i = input('faça sua pesquisa de tipo aqui:')
print(type(i))
print('é numerico?', i.isnumeric())
print('é alfabetico?', i.isalpha())
print('esta em maiusculo?', i.isupper())
print('é alfanumerico?', i.isalnum())
print('esta em minusculo?', i.islower())
print('só tem espaço?', i.isspace())
print('esta capitalizada?', i.istitle())
print('capitalizada é quando tem letra maiuscula e minuscula')
print('esta em ASCII?', i.isascii())
print('esta em decimal?', i.isdecimal())
print('todos os digitos são visiveis?', i.isidentifier())
print('tem digitos não visiveis e simbolos ex.nulo, asterisco?', i.isprintable())
