print('=====seja, bem vindo!!!=====')
nome = input('digite seu nome:')
print('obrigado por estar aqui comigo,',nome)
print('=====segundo desafio=====')
d = input('que dia você nasceu?')
m = input('e o mês?')
a = input('o ano?')
print('muito bem,então você nasceu no dia {} , do mês {}, e ano {}'.format(d, m, a))
print('=====terceiro desafio=====')
n1 = int(input('digite um numero:'))
n2 = int(input('digite outro numero:'))
print('a soma de {} + {} é {}'.format(n1,n2,(n1+n2)))
